FROM node:current-slim

MAINTAINER Joshua S. Eagle

WORKDIR /root/

# Update NPM
RUN npm cache clean -f

COPY ./node-service /root/node-service/

WORKDIR /root/node-service/

RUN npm install --silent

EXPOSE 5000

CMD ["npm", "run", "prod"]
