version: "3.3"

services:
  node-service:
    build:
      context: .
      dockerfile: Dockerfile.node-service
    command: ["npm", "run", "prod"]
    image: spell-watcher/node-service:latest
    volumes:
      - ./node-service:/root/spell-watcher/node-service
    ports:
      - 5000
    restart: always
    container_name: node-service

  nginx:
    image: nginx:latest
    command: []
    volumes:
      - ./ng-app/dist/spell-watcher-ui/:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    restart: always
    container_name: nginx

  reverseproxy:
    image: nginx:latest
    volumes:
      - ./nginx.reverseproxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5000:5000
    restart: always
    container_name: reverseproxy
