version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.ng-app
    command: ['npm', 'run', 'docker-start']
    image: spell-watcher/ng-app:latest
    volumes:
      - ./ng-app/src/:/root/ng-app/src/
    ports:
      - 4200:4200
      - 9876:9876
    environment:
      - DISPLAY=:99
      - CHROME_BIN=chromium
    restart: always
    container_name: ng-app
  node-service:
    build:
      context: .
      dockerfile: Dockerfile.node-service
    command: ['npm', 'run', 'start-debug']
    image: spell-watcher/node-service:latest
    volumes:
      - ./node-service:/root/spell-watcher/node-service
    ports:
      - 8080:8080
      - 9229:9299
    restart: always
    container_name: node-service