FROM node:current-slim

MAINTAINER Joshua S. Eagle

WORKDIR /root/

# Update NPM
RUN npm cache clean -f

COPY ./node-service /root/node-service/

WORKDIR /root/node-service/

RUN npm install -g nodemon

RUN npm install --silent

EXPOSE 8080

CMD ["npm", "run", "start-be"]
