version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod.ng-app
    image: eaglejs/spell-watcher-web:latest
    command: []
    ports:
      - 80:80
    restart: always
    container_name: nginx

  node-service:
    command: ["npm", "run", "prod"]
    build:
      context: .
      dockerfile: Dockerfile.node-service
    image: eaglejs/spell-watcher-node-service:latest
    ports:
      - 5000
    restart: always
    container_name: node-service

  reverseproxy:
    build:
      context: .
      dockerfile: Dockerfile.prod.reverseproxy
    image: eaglejs/spell-watcher-reverseproxy:latest
    ports:
      - 5000:5000
    restart: always
    container_name: reverseproxy
